services:
  nginx:
    image: tiangolo/nginx-rtmp:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./index.html:/usr/share/nginx/html/index.html
      - ./stream:/hls/live
    ports:
      - "1935:1935"
      - "80:80"